---
- name: Check OS and kernel version
  hosts: all
  tasks:
    - name: Gather facts
      gather_facts: yes
    
    - name: Display OS version
      debug:
        msg: "OS version on {{ ansible_hostname }} is {{ ansible_distribution }} {{ ansible_distribution_version }}"
    
    - name: Display kernel version
      debug:
        msg: "Kernel version on {{ ansible_hostname }} is {{ ansible_kernel }}"
...