---
- name: Update packages
  hosts: all
  tasks:
    - name: Update apt packages (for Ubuntu)
      apt:
        upgrade: yes
      when: ansible_distribution == 'Ubuntu'
    
    - name: Update yum packages (for Oracle)
      yum:
        name: '*'
        state: latest
      when: ansible_distribution == 'OracleLinux'
...